---
title: "links_to_other_code_resources"
author: "Thomas Cattiaux"
date: "2025-05-23"
output: html_document
---
# Links to other code resources

This section refers to already published manuscripts for which codes are publicly available. They are classified in chronological order.

## Oct21: Mutographs ESCC Manuscript

Mutographs ESCC Manuscript was published in Nature Genetics in October 2021 (https://www.nature.com/articles/s41588-021-00928-6). It included the analysis of 552 genomes from esophageal squamous cell carcinoma patients The downstream analyses codes are available at https://gitlab.com/Mutographs/Mutographs_ESCC

### Code authors: 
* Epidemiological associations: Sergey Senkin (http://git.iarc.lan/senkins)
* Germline annotations and analysis: Joshua Atkins, Ricardo Cortez Cardoso Penha
* Signature extractions and attributions: Sarah Moody, Sergey Senkin

## May24: Mutographs RCC Manuscript

Mutographs RCC Manuscript was published in Nature in May 2024 (https://www.nature.com/articles/s41586-024-07368-2). It included the analysis of 962 genomes from clear cell renal cell carcinoma patients. The downstream analyses codes are available at https://gitlab.com/Mutographs/Mutographs_RCC

### Code authors:
* Epidemiological associations: Sergey Senkin (http://git.iarc.lan/senkins)
* Germline annotations and analysis: Joshua Atkins, Ricardo Cortez Cardoso Penha
* Signature extractions and attributions: Sarah Moody, Sergey Senkin
* Metabolomics analysis: Thomas Cattiaux (https://github.com/cattiauxt)
* Geospatial analysis: Thomas Cattiaux

